name: "Create docker image & push to "
description: "Create docker image and push to "
inputs:
  docker_username:
    description: "username of docker account"
    required: true
  docker_password:
    description: "password of docker account"
    required: true
runs:
  using: "composite"
  steps:
    - name: Say Username
      run: echo "The message is ${{ inputs.docker_username }}"
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: inputs.docker_username
        password: inputs.docker_password

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: inputs.docker_username/va:testing
