name: "Build and push to docker repo"
description: "Create a docker image and push to docker repo"
inputs:
  gcp_sa_key:
    description: "key"
    required: true
  gcp_project_id:
    description: "project id"
    required: true
  registry:
    description: "registry of the repository"
    required: true
  image_name:
    description: "name of the image"
    required: true
  tag:
    description: "tag of the image"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Google Cloud Auth
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.JSONKEY }}"
        project_id: "back-438814"

    - name: Set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v2"

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t "us-central1-docker.pkg.dev/back-438814/dummytest/myimage":latest -f Dockerfile .
        docker push "us-central1-docker.pkg.dev/back-438814/dummytest/myimage":latest
