name: "Create docker image & push to "
description: "Create docker image and push to "
inputs:
  dockerusername:
    description: "username of docker account"
    required: true
  dockerpassword:
    description: "password of docker account"
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: inputs.dockerusername
        password: inputs.dockerpassword

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: inputs.dockerusername/va:testing
