name: "Build and push to docker repo"
description: "Create a docker image and push to docker repo"
inputs:
  docker_username:
    description: "username of docker account"
    required: true
  docker_password:
    description: "password of docker account"
    required: true
  repository_name:
    description: "name of the repository"
    required: true
  tag:
    description: "tag of the image"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ inputs.docker_username }}/${{ inputs.repository_name }}:${{ inputs.tag }}
