name: "Update YAML with Kustomize"
description: "Custom action to patch a YAML file in another repo using kustomize"

inputs:
  repo:
    description: "Target repository (owner/repo)"
    required: true
  branch:
    description: "Target branch"
    required: false
    default: "main"
  file_path:
    description: "Path to kustomization.yaml"
    required: true
  image_name:
    description: "Container image name"
    required: true
  image_tag:
    description: "Container image tag"
    required: true
  github_token:
    description: "GitHub token with write access to target repo"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.github_token }}
        path: state-files-repo

    - name: Debug repo contents
      run: |
        ls -R state-files-repo | head -50

    - name: Install Kustomize
      shell: bash
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Update kustomization.yaml
      shell: bash
      run: |
        echo "➡️ Updating file: ${{ inputs.file_path }}"
        echo "➡️ Setting image: ${{ inputs.image_name }}:${{ inputs.image_tag }}"

        cd "$(dirname "${{ inputs.file_path }}")"
        kustomize edit set image "${{ inputs.image_name }}=${{ inputs.image_name }}:${{ inputs.image_tag }}"

        echo "✅ kustomization.yaml updated successfully"

    - name: Commit & Push
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.file_path }}"
        git commit -m "chore: update image ${{ inputs.image_name }}:${{ inputs.image_tag }}" || echo "No changes to commit"
        git push origin ${{ inputs.branch }}

    - name: After
      shell: bash
      run: |
        echo "✅ DONE"
