name: "Update image to state-file"
description: "Update image to state-file"
inputs:
  image_tag_name:
    description: "image_tag_name"
    required: true
  image_name:
    description: "image_name"
    required: true
  environment:
    description: "environment"
    required: true
  bitbucket_username:
    description: "bitbucket username"
    required: true
  bitbucket_app_pwd:
    description: "bitbucket app password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clonar el repositorio de Bitbucket
      shell: bash
      run: |
        git clone https://${{ inputs.bitbucket_username }}:${{ inputs.bitbucket_app_pwd }}@bitbucket.org/dqworkspace/state_file_repo.git
      env:
        GIT_SSL_NO_VERIFY: true

    - name: Instalar yq
      shell: bash
      run: sudo snap install yq

    #- name: List all files in repo
    #  shell: bash
    #  run: |
    #    echo "📦 Archivos en el repositorio:"
    #    find . -type f

    - name: Update or create image tag in state files
      shell: bash
      run: |
        FILE="./cde/myapp/qa/kustomization.yaml"
        yq e '(.images[] | select(.name == "${{ inputs.image_name }}")).newTag = "${{ inputs.image_tag_name }}"' -i $FILE

    #- name: Actualizar newTag en YAML
    #  shell: bash
    #  run: |
    #    yq e '(.images[] | select(.name == "gcr.io/transfers-non-cde-3df5/l2p/alias-directory-gw/release")).newTag = "${{ inputs.image_tag_name }}"' -i $FILE

    - name: Commit y push a Bitbucket
      shell: bash
      run: |

        git config user.name ${{ inputs.bitbucket_username }}
        git config user.email "dquinonezlib@gmail.com"
        git add .
        git commit -m "chore: update image tag to "
        git push origin
