name: "Update image to state-file"
description: "Update image to state-file"
inputs:
  image_tag_name:
    description: "image_tag_name"
    required: true
  environment:
    description: "environment"
    required: true
  gh_pat:
    description: "gh_pat"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifacts (state files) todo
      uses: actions/download-artifact@v4
      with:
        name: environment-setup-artifact
        path: ./state-files

    - name: Clone state files repository todo
      shell: bash
      run: |
        git clone https://github.com/QUIDA5V/state-files-repo.git
        mv ./state-files/* ./state-files-repo

    - name: Update image tag in state files todo
      shell: bash
      run: |
        find ./state-files-repo/qa -type f -name "data.json" -exec sed -i "s/\"imageTag\": \".*\"/\"imageTag\": \"${{ inputs.image_tag_name }}\"/" {} \;

    - name: Set up Git credentials todo
      shell: bash
      run: |
        git config --global user.email "dquinonezlib@gmail.com"
        git config --global user.name "QUIDA5V"

    - name: Commit and push changes todo
      shell: bash
      run: |
        cd ./state-files-repo
        git remote set-url origin https://x-access-token:${{ inputs.gh_pat }}@github.com/QUIDA5V/state-files-repo
        git add .
        git commit -m "Update image tag to test"
        git push origin HEAD
