name: "Update state-file tag name"
description: "Update state-file tag name"
inputs:
  image_tag_name:
    description: "tag name of the image"
    required: true
  image_name:
    description: "name of the image"
    required: true
  repo_name:
    description: "name of the state file repo"
    required: true
  organization_workspace:
    description: "name of workspace organization"
    required: true
  src_file:
    description: "address of the state file"
    required: true
  bitbucket_username:
    description: "bitbucket username"
    required: true
  bitbucket_user_email:
    description: "bitbucket user email"
    required: true
  bitbucket_app_pwd:
    description: "bitbucket app password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone Bitbucket repository
      shell: bash
      run: |
        git clone https://${{ inputs.bitbucket_username }}:${{ inputs.bitbucket_app_pwd }}@bitbucket.org/${{ inputs.organization_workspace }}/${{ inputs.repo_name }}.git bitbucket-repo
      env:
        GIT_SSL_NO_VERIFY: true

    - name: Install yq
      shell: bash
      run: sudo snap install yq

    - name: Update image tag in state files
      shell: bash
      run: |
        FILE="./bitbucket-repo/${{ inputs.src_file }}"
        yq e '(.images[] | select(.name == "${{ inputs.image_name }}")).newTag = "${{ inputs.image_tag_name }}"' -i $FILE

    - name: Commit and push to Bitbucket
      shell: bash
      run: |
        cd bitbucket-repo
        git config user.name ${{ inputs.bitbucket_username }}
        git config user.email ${{ inputs.bitbucket_user_email }}
        git add .
        git commit -m ":pencil2: update image tag of ${{ inputs.image_name }}"
        git push origin
