name: "Update YAML with Kustomize"
description: "Custom action to patch a YAML file in another repo using kustomize"

inputs:
  repo:
    description: "Target repository (owner/repo)"
    required: true
  branch:
    description: "Target branch"
    required: false
    default: "main"
  file_path:
    description: "Directory containing kustomization.yaml"
    required: true
  image_name:
    description: "Container image name"
    required: true
  image_tag:
    description: "Container image tag"
    required: true
  github_token:
    description: "GitHub token with write access to target repo"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        token: ${{ inputs.github_token }}

    - name: Install Kustomize
      shell: bash # 👈 obligatorio
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Run update script
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
        $GITHUB_ACTION_PATH/entrypoint.sh \
          "${{ inputs.file_path }}" \
          "${{ inputs.image_name }}" \
          "${{ inputs.image_tag }}"

    - name: Commit & Push
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.file_path }}"
        git commit -m "chore: update image ${{ inputs.image_name }}:${{ inputs.image_tag }}" || echo "No changes"
        git push origin ${{ inputs.branch }}
