name: "Update image to state-file"
description: "Update image to state-file"
inputs:
  image_tag_name:
    description: "image_tag_name"
    required: true
  image_name:
    description: "image_name"
    required: true
  environment:
    description: "environment"
    required: true
  bitbucket_username:
    description: "bitbucket username"
    required: true
  bitbucket_app_pwd:
    description: "bitbucket app password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clonar el repositorio de Bitbucket
      shell: bash
      run: |
        git clone https://${{ inputs.bitbucket_username }}:${{ inputs.bitbucket_app_pwd }}@bitbucket.org/dqworkspace/state_file_repo.git bitbucket-repo
      env:
        GIT_SSL_NO_VERIFY: true

    - name: Instalar yq
      shell: bash
      run: sudo snap install yq

    - name: Actualizar newTag en YAML
      shell: bash
      run: |
        yq e '(.images[] | select(.name == "gcr.io/transfers-non-cde-3df5/l2p/alias-directory-gw/release")).newTag = "${{ inputs.image_tag_name }}"' -i kustomization.yaml

    - name: Commit y push a Bitbucket
      shell: bash
      run: |
        cd bitbucket-repo
        git config user.name "daniel quinonez"
        git config user.email "dquinonezlib@gmail.com"
        git add .
        git commit -m "chore: update image tag to "
        git push origin main
